### ISSUE TITLE
docs: add missing documentation

### ISSUE THREAD

**Issue by jelledouwe** [eager-dev/eagerx#142]
### 📚 Documentation

The documentation can be improved as follows:

- [x] Add documentation in the developer guide on Converters
- [x] Add documentation in the developer guide on Processors
- [x] Add documentation in the developer guide on EngineGraphs
- [x] Add code examples/colabs
- [x] Add GIF GUI
- [x] Add GIFs pendulum tutorial
- [x] Add EngineGraph.gui() to documentation
- [x] Add info on $(config param) syntax
- [x] Add comment that all rospy functions can be used
- [x] Add rqt_plot, rosbag support
- [x] Add info on check_validity plots

### Checklist

- [x] I have read the [documentation](https://eagerx.readthedocs.io) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/eager-dev/eagerx/issues) in the repo (**required**)

**Comment by bheijden** [comment]
Erron

**Comment by bheijden** [comment]
These points have been included in either the developer guide or colab examples.
