### ISSUE TITLE
Warning missing in the doc about ROS2

### ISSUE THREAD

**Issue by araffin** [eager-dev/eagerx#146]
### 📚 Documentation

ROS2 is not supported, must be probably put as a warning in the doc and the readme.

### Checklist

- [x] I have read the [documentation](https://eagerx.readthedocs.io) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/eager-dev/eagerx/issues) in the repo (**required**)

**Comment by bheijden** [comment]
Closed by #147.
