### ISSUE TITLE
[Bug] `GymObject` is slower than expected.

### ISSUE THREAD

**Issue by bheijden** [eager-dev/eagerx#180]
### 🐛 Bug

It appears that the `GymObject` is suddenly very slow. Find out what release has made it so slow.

### To Reproduce

Run an experiment with the GymBridge and GymObject.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/eager-dev/eagerx/issues) in the repo (**required**)
- [x] I have read the [documentation](https://eagerx.readthedocs.io) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by jelledouwe** [comment]
Close because this issue cannot be reproduced.
