### ISSUE TITLE
[Bug] Synchronization issue with pendulum

### ISSUE THREAD

**Issue by bheijden** [eager-dev/eagerx#233]
### 🐛 Bug

In `sync` mode, the message seem to be shifted which breaks performance in the pendulum task.

### To Reproduce

Evaluate a policy trained with the OpenAI gym pendulum on the real pendulum of the `eagerx_dcsc_setups`.

Use `rqt_plot` to visualize `<env_id>/environment/outputs/voltage/data[0]` and `<env_id>/pendulum/u/outputs/u/data[0]`.

If we also include the reset node, you can also visualize the action feedthrough with `<env_id>/reset_angle/outputs/u/data[0]`.

Make sure that:
- No rendering
- No applied_action engine node
- Run synchronized mode

Observations:
- First episode seems to lag 1 time step if no reset node is selected. If, after the initial reset, you apply a single action directly followed by a reset, this effect is mitigated. Why is the initial episode systematically shifted? Perhaps use `rostopic echo` to view all published messages in the initial episode. If the mismatch is not visible between the commanded and applied action, the shift might exist in the observation. This would mean that a delayed observation is passed, instead of the most recent one.
- If the `reset_node` is additionally included, the asynchronous effect is more visible. With rqt_plot you can see  a clear mismatch between the commanded and applied action.

### System Info

Describe the characteristic of your environment:
 * Poetry
 * eagerx=0.1.33
 * Python=3.8
 * eagerx_dcsc_setups=0.1.14
 * backend=ROS

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/eager-dev/eagerx/issues) in the repo (**required**)
- [x] I have read the [documentation](https://eagerx.readthedocs.io) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by jelledouwe** [comment]
Solved by #254

**Comment by jelledouwe** [comment]
Solved by #254
